Repository zendframework/zend-form, pull requests merged in 2018-12, with the labels that each got.

#207 Fieldset#get(): Update return type options
  src/Fieldset.php
Labels: documentation

#208 Documentation of form-collection: explaining $wrap param
  docs/book/helper/form-collection.md
Labels: documentation

#214 Test for #83 bindValues not working after prepare
  test/FormTest.php
Labels: Test

#218 Fix rendering select element when value is an object
  CHANGELOG.md
  src/View/Helper/FormSelect.php
  test/TestAsset/Identifier.php
  test/View/Helper/FormSelectTest.php
Labels: bug

#219 Document attributes on options of select element
  docs/book/element/select.md
Labels: documentation, enhancement
